class CommonMimetypes:
    PDF = 'application/pdf'
    TXT = 'text/plain'
    DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    DOC = 'application/msword'
    XLS = 'application/vnd.ms-excel'
    PPT = 'application/vnd.ms-powerpoint'
    CSV = 'text/csv'
