"""Collection sharing level

Revision ID: 712af525a5ab
Revises: bdbce7007fb2
Create Date: 2025-01-11 13:54:38.755816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712af525a5ab'
down_revision: Union[str, None] = 'bdbce7007fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('sharing_level', sa.Enum('ORG', 'PRIVATE', 'LIMITED', name='sharinglevel'), server_default='ORG', nullable=False))
    op.add_column('collections', sa.Column('shared_with', sa.JSON(), nullable=True))
    op.add_column('collections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_collections_user_id_users'), 'collections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_collections_user_id_users'), 'collections', type_='foreignkey')
    op.drop_column('collections', 'user_id')
    op.drop_column('collections', 'shared_with')
    op.drop_column('collections', 'sharing_level')
    # ### end Alembic commands ###
