"""Initial

Revision ID: bdbce7007fb2
Revises:
Create Date: 2024-12-16 15:42:19.984249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdbce7007fb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('metatadata_prompt_prelude', mysql.TEXT(), nullable=True),
    sa.Column('metatadata_prompt', mysql.TEXT(), nullable=True),
    sa.Column('custom_instructions', mysql.TEXT(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('collection_rule', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('docchat_faq',
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.Column('faq_question', mysql.TEXT(), nullable=False),
    sa.Column('faq_answer', mysql.LONGTEXT(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_table('docchat_metadata',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=256), nullable=False),
    sa.Column('value', mysql.LONGTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'collection_id', 'file_id', 'schema_id')
    )
    op.create_index('unique_file_id_and_schema_id', 'docchat_metadata', ['file_id', 'schema_id'], unique=True)
    op.create_table('docchat_metadata_schema',
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=256), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_index('collection_id', 'docchat_metadata_schema', ['collection_id', 'field'], unique=True)
    op.create_index('schema_id_UNIQUE', 'docchat_metadata_schema', ['schema_id'], unique=True)
    op.create_table('docguide_faq',
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.Column('faq_title', sa.String(length=256), nullable=False),
    sa.Column('faq_content', mysql.TEXT(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_table('docguide_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('doc_file_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('docguide_sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=64), nullable=False),
    sa.Column('section_content', mysql.TEXT(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('docguide_sections_learned_status',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('learned_status', mysql.ENUM('INITIAL', 'PARTIAL', 'FULL'), nullable=False),
    sa.Column('assessment_score', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'user_id', 'section_id')
    )
    op.create_index('org_id', 'docguide_sections_learned_status', ['org_id', 'user_id', 'section_id'], unique=True)
    op.create_table('entities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('data', mysql.LONGTEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('json_valid(`data`)', name='data_valid_json'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_configurations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', mysql.LONGTEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('json_valid(`config`)', name='config_valid_json'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('type', 'entity_configurations', ['type'], unique=True)
    op.create_table('files_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary_short', sa.String(length=500), nullable=True),
    sa.Column('summary_long', sa.String(length=4000), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files_metadata_plus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('creator_username', sa.String(length=50), nullable=True),
    sa.Column('updater_username', sa.String(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_ai_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_start', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('user_content', sa.Text(), nullable=True),
    sa.Column('system_content', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('timestamp_end', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('username', 'log_ai_calls', ['username'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('button_text', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_action', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_name', 'modules', ['name'], unique=True)
    op.create_table('organization',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('org_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED'), server_default=sa.text("'ACTIVE'"), nullable=True),
    sa.Column('logo_url', mysql.VARCHAR(length=190), nullable=True),
    sa.Column('home_module_function_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('vector_provider', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index('org_name', 'organization', ['org_name'], unique=True)
    op.create_table('organization_modules',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'module_id')
    )
    op.create_index('module_id', 'organization_modules', ['module_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.String(length=300), nullable=False),
    sa.Column('prompt_name', sa.String(length=300), nullable=False),
    sa.Column('name_label', sa.String(length=300), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.String(length=300), nullable=False),
    sa.Column('prompt_name', sa.String(length=300), nullable=False),
    sa.Column('name_label', sa.String(length=300), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_organization',
    sa.Column('user_id', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('org_id', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('role', mysql.ENUM('MEMBER', 'ADMIN', 'GUEST', 'SUPER_USER'), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('join_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=300), nullable=True),
    sa.Column('objectives', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_name', 'user_roles', ['role_name'], unique=False)
    op.create_index('idx_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_joined', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('profile_picture_url', mysql.VARCHAR(length=190), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_table('collections_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['collections.collection_id'], name='fk_insights_collection_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('upload_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name='fk_collection_id'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('fk_collection_id', 'files', ['collection_id'], unique=False)
    op.create_table('organization_collections',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name='organization_collections_ibfk_2'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], name='organization_collections_ibfk_1'),
    sa.PrimaryKeyConstraint('org_id', 'collection_id')
    )
    op.create_index('collection_id', 'organization_collections', ['collection_id'], unique=False)
    op.create_table('user_role_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_role_current_ibfk_2'),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], name='user_role_current_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_id', 'user_role_current', ['user_id'], unique=False)
    op.create_index('user_role_id', 'user_role_current', ['user_role_id'], unique=False)
    op.create_table('user_role_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_role_history_ibfk_2'),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], name='user_role_history_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_id', 'user_role_history', ['user_id'], unique=False)
    op.create_index('user_role_id', 'user_role_history', ['user_role_id'], unique=False)
    op.create_table('files_bm25_meta',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('avg_doc_len', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], name='files_bm25_meta_ibfk_1'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('files_bm25_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('idf', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], name='files_bm25_terms_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('file_id', 'files_bm25_terms', ['file_id'], unique=False)
    op.create_table('files_collections',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], name='files_collections_ibfk_2'),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], name='files_collections_ibfk_1'),
    sa.PrimaryKeyConstraint('file_id', 'collection_id')
    )
    op.create_index('collection_id', 'files_collections', ['collection_id'], unique=False)
    op.create_table('files_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], name='files_pages_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('file_id', 'files_pages', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('file_id', table_name='files_pages')
    op.drop_table('files_pages')
    op.drop_index('collection_id', table_name='files_collections')
    op.drop_table('files_collections')
    op.drop_index('file_id', table_name='files_bm25_terms')
    op.drop_table('files_bm25_terms')
    op.drop_table('files_bm25_meta')
    op.drop_index('user_role_id', table_name='user_role_history')
    op.drop_index('user_id', table_name='user_role_history')
    op.drop_table('user_role_history')
    op.drop_index('user_role_id', table_name='user_role_current')
    op.drop_index('user_id', table_name='user_role_current')
    op.drop_table('user_role_current')
    op.drop_index('collection_id', table_name='organization_collections')
    op.drop_table('organization_collections')
    op.drop_index('fk_collection_id', table_name='files')
    op.drop_table('files')
    op.drop_table('collections_insights')
    op.drop_index('username', table_name='users')
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_user_id', table_name='user_roles')
    op.drop_index('idx_role_name', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('user_organization')
    op.drop_table('prompts_archive')
    op.drop_table('prompts')
    op.drop_index('module_id', table_name='organization_modules')
    op.drop_table('organization_modules')
    op.drop_index('org_name', table_name='organization')
    op.drop_table('organization')
    op.drop_index('idx_name', table_name='modules')
    op.drop_table('modules')
    op.drop_index('username', table_name='log_ai_calls')
    op.drop_table('log_ai_calls')
    op.drop_table('jobs')
    op.drop_table('files_metadata_plus')
    op.drop_table('files_metadata')
    op.drop_index('type', table_name='entity_configurations')
    op.drop_table('entity_configurations')
    op.drop_table('entities')
    op.drop_index('org_id', table_name='docguide_sections_learned_status')
    op.drop_table('docguide_sections_learned_status')
    op.drop_table('docguide_sections')
    op.drop_table('docguide_files')
    op.drop_table('docguide_faq')
    op.drop_index('schema_id_UNIQUE', table_name='docchat_metadata_schema')
    op.drop_index('collection_id', table_name='docchat_metadata_schema')
    op.drop_table('docchat_metadata_schema')
    op.drop_index('unique_file_id_and_schema_id', table_name='docchat_metadata')
    op.drop_table('docchat_metadata')
    op.drop_table('docchat_faq')
    op.drop_table('collections')
    # ### end Alembic commands ###
